spring:
  profiles:
    active: dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: SpringCloud-Config-Client
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
---
server:
  port: 8201

spring:
  profiles: test
  application:
    name: SpringCloud-Config-Client
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/